site_name: WWIV BBS
repo_url: https://github.com/wwivbbs/docs/
copyright: 2014+ WWIV Software Services, LLC
docs_dir: docs
theme: readthedocs
pages:
    - 'Home': index.md
    - Installation:
        - 'Windows Installation': windows_installation.md
        - 'Linux Installation': linux_installation.md
        - 'Linux dosemu scripts': linux_dosemu_scripts.md
        - 'Linux dosemu settings': linux_dosemu_settings.md
        - 'Upgrading WWIV 4.x': wwiv_4x_upgrade.md
    - Configuration:
        - 'Init.exe': init.md
        - 'WWIV.ini': wwivini.md
        - 'Displaying Text': displaying_text.md
        - 'Other Config Files': config_files.md
        - '.log Files': logfiles.md
        - 'multinode': multinode.md
        - 'taglines': taglines.md
        - 'fail2ban IP blocking': fail2ban.md
        - Telnet:
            - 'WWIV 5 Telnet Server': wwiv_5_telnet_server.md    
            - 'NET2BBS': net2bbs.md
        - Menus & Features:
            - 'Main menu': main_menu.md
            - 'Messaging system': messaging_system.md
            - 'User preferences': user_preferences.md
            - 'G-Files': gfiles.md
            - 'transfers': transfers.md
            - 'Waiting for callers': waiting_for_callers.md
            - '// (slash) Menu': slash_menu.md
            - '//SysOp Menu': sysop_menu.md
            - 'Event Management': eventmgmt.md
        - Nets:
            - 'WWIVnet Overview': wwivnet.md
            - 'WWIVnet on Windows': wwivnet_windows.md
            - 'WWIVnet on Linux': wwivnet_linux.md
            - 'Other Nets': other_nets.md
            - 'USENET':  usenet.md
            - 'NET37 Docs': net37_docs.md
            - 'NET37 Tec Docs': net37_tec_docs.md
        - Doors & Chains:
            - 'Doors & Chains Overview': doors.md
            - 'Ambroshia': ambroshia.md
            - 'Barron Realms Elite': barron_realms_elite.md
            - 'Darkness': darkness.md
            - 'DoorMUD': doormud.md
            - 'Planets: The Exploration of Space': doorteos.md
            - 'LORD': lord.md
            - 'LORD2': lord2.md
            - 'MechWars': mechwars.md
            - 'TradeWars2002': tradewars2002.md
        - Editors:
            - 'WWIVEdit': wwivedit.md
            - 'QuickBBS-Editors': quickbbs-editors.md
        - Tools and Utilities:
            - 'clients': clients.md
            - 'FIX.exe Utility': fix.md
    - About:
      - 'WWIV BBS list': wwiv_bbs_list.md
      - 'license': license.md
      - History of WWIV:
          - 'In the Beginning....': history.md
          - 'WWIV Open Source Announcement': wwiv_open_source_announcement.md
          - 'newsysop': newsysop.md
          - 'Original-Ideas-for-5.0-from-July-1999': original-ideas-for-5.0-from-july-1999.md
          - 'links': links.md
      - WWIVCon:
          - 'WWIVCon 1994': wwivcon_1994.md
          - 'WWIVCon 1995': wwivcon_1995.md
          - 'WWIVCon 1996': wwivcon_1996.md
          - 'WWIVCon 1997': wwivcon_1997.md
          - 'WWIVCon 1998': wwivcon_1998.md
          - 'WWIVCon 1999': wwivcon_1999.md
      - Development:
          - 'How to Build WWIV 5': build_wwiv_5.md
          - 'WWIV Releases & Versioning': wwiv_releases_and_versioning.md
        
