site_name: WWIV BBS 5.0 Documentation
repo_url: https://github.com/wwivbbs/docs/
copyright: 2014+ WWIV Software Services, LLC
docs_dir: docs
pages:
    - 'index.md'
    - 'WWIV_BBS_list.md'
    - 'license.md'
    - Installation:
        - 'Installing_on_Windows.md'
        - 'WWIV_4x_Upgrade.md'
        - 'Linux_Installation.md'
        - 'Linux_dosemu_scripts.md'
        - 'Linux_dosemu_settings.md'
    - Configuration:
        - 'Custom_user_messages.md'
        - 'dialup.md'
        - 'init.md'
        - 'logfiles.md'
        - 'multinode.md'
        - 'taglines.md'
        - 'wwivini.md'
    - Telnet:
        - 'WWIV_5_telnet_server.md'    
        - 'NET2BBS.md'
    - Menus & Features:
        - 'ansi.md'
        - 'eventmgmt.md'
        - 'gfiles.md'
        - 'Main_menu.md'
        - 'Messaging_system.md'
        - 'Slash_menu.md'
        - 'SysOp_menu.md'
        - 'transfers.md'
        - 'User_preferences.md'
        - 'Waiting_for_callers.md'
    - Nets:
        - 'WWIVNet.md'
        - 'WWIVNet_Windows.md'
        - 'Other_Nets.md'
        - 'WWIVNet_Linux.md'
        - 'usenet.md'
        - 'NET37_Docs.md'
        - 'NET37_Tec_Docs.md'
    - Doors & Chains:
        - 'Ambroshia.md'
        - 'BarronRealmsElite.md'
        - 'Darkness.md'
        - 'DoorMUD.md'
        - 'doorteos.md'
        - 'doors.md'
        - 'LORD.md'
        - 'LORD2.md'
        - 'MechWars.md'
        - 'TradeWars2002.md'
    - Editors:
        - 'wwivedit.md'
        - 'QuickBBS-Editors.md'
    - Tools and Utilities:
        - 'clients.md'
        - 'fix.md'
    - History:
        - 'history.md'
        - 'WWIV_Open_Source_Announcement.md'
        - 'newsysop.md'
        - 'Original-Ideas-for-5.0-from-July-1999.md'
        - 'links.md'
    - Development:
        - 'build_WWIV_5.md'
        - 'wwiv_releases_and_versioning'
    - WWIVCon:
        - 'WWIVCon_1994.md'
        - 'WWIVCon_1995.md'
        - 'WWIVCon_1996.md'
        - 'WWIVCon_1997.md'
        - 'WWIVCon_1998.md'
        - 'WWIVCon_1999.md'
    - WWIVNews:
        - 'WWIVNews.md'
        - 'WWIVNews_201512.md'
        - 'WWIVNews_2015_12.md'
        - 'WWIVNews_1996_Spring.md'
        - 'WWIVNews_1995_12.md'
        - 'WWIVNews_1995_09.md'
        - 'WWIVNews_1995_05.md'
        - 'WWIVNews_1994_03.md'
        - 'WWIVNews_1994_01.md'
        - 'WWIVNews_1993_06.md'
        - 'WWIVNews_1993_04.md'
        - 'WWIVNews_1993_02.md'
        - 'WWIVNews_199201.md'
        - 'WWIVNews_1992_11.md'
        - 'WWIVNews_1992_10.md'
        - 'WWIVNews_1992_09.md'
        - 'WWIVNews_1992_08.md'
        - 'WWIVNews_1992_07.md'
        - 'WWIVNews_1992_06.md'
        - 'WWIVNews_1992_05.md'
        - 'WWIVNews_1992_01.md'
        - 'WWIVNews_1991_08.md'
        - 'WWIVNews_1991_06.md'
        - 'WWIVNews_1991_05.md'
        - 'WWIVNews_1991_04.md'
        - 'WWIVNews_1991_03.md'
        - 'WWIVNews_1991_02.md'
        - 'WWIVNews_1991_01.md'
        - 'WWIVNews_Template.md'
        - 'WWIVNews_Playbook.md'