site_name: WWIV BBS 5.0 Documentation
repo_url: https://github.com/wwivbbs/docs/
copyright: 2014+ WWIV Software Services, LLC
docs_dir: docs
pages:
    - 'index.md'
    - 'WWIV_BBS_list.md'
    - 'license.md'
    - Installation:
        - 'Installing_on_Windows.md'
        - 'WWIV_4x_Upgrade.md'
        - 'Linux_Installation.md'
        - 'Linux_dosemu_scripts.md'
        - 'Linux_dosemu_settings.md'
    - Configuration:
        - 'Init.exe': 'init.md'
        - 'WWIV.ini': 'wwivini.md'
        - 'Custom_user_messages.md'
        - 'Dial-Up Modems': 'dialup.md'
        - '.log Files': 'logfiles.md'
        - 'multinode.md'
        - 'taglines.md'
    - Telnet:
        - 'WWIV 5 Telnet Server': 'WWIV_5_telnet_server.md'    
        - 'NET2BBS.md'
    - Menus & Features:
        - 'Main_menu.md'
        - 'Messaging_system.md'
        - 'User_preferences.md'
        - 'ANSI Colors': 'ansi.md'
        - 'G-Files': 'gfiles.md'
        - 'transfers.md'
        - 'Waiting_for_callers.md'
        - '\\ (slash) Menu': 'Slash_menu.md'
        - '\\ SysOp Menu': 'SysOp_menu.md'
        - 'Event Management': 'eventmgmt.md'
    - Nets:
        - 'WWIVNet Overview': 'WWIVNet.md'
        - 'WWIVNet on Windows': 'WWIVNet_Windows.md'
        - 'WWIVNet on Linux': 'WWIVNet_Linux.md'
        - 'Other_Nets.md'
        - 'USENET': 'usenet.md'
        - 'NET37_Docs.md'
        - 'NET37_Tec_Docs.md'
    - Doors & Chains:
        - 'Doors & Chains Overview': 'doors.md'
        - 'Ambroshia.md'
        - 'BarronRealmsElite.md'
        - 'Darkness.md'
        - 'DoorMUD.md'
        - 'doorteos.md'
        - 'LORD.md'
        - 'LORD2.md'
        - 'MechWars.md'
        - 'TradeWars2002.md'
    - Editors:
        - 'wwivedit.md'
        - 'QuickBBS-Editors.md'
    - Tools and Utilities:
        - 'clients.md'
        - 'FIX.exe Utility': 'fix.md'
    - History of WWIV:
        - 'In the Beginning....': 'history.md'
        - 'WWIV_Open_Source_Announcement.md'
        - 'newsysop.md'
        - 'Original-Ideas-for-5.0-from-July-1999.md'
        - 'links.md'
    - Development:
        - 'How to Build WWIV 5': 'build_WWIV_5.md'
        - 'WWIV Releases & Versioning': 'wwiv_releases_and_versioning.md'
    - WWIVCon:
        - 'WWIVCon_1994.md'
        - 'WWIVCon_1995.md'
        - 'WWIVCon_1996.md'
        - 'WWIVCon_1997.md'
        - 'WWIVCon_1998.md'
        - 'WWIVCon_1999.md'
    - WWIVNews Archive:
        - 'WWIVNews History': 'WWIVNews.md'
        - 'WWIVNews_2015_12.md'
        - 'WWIVNews_1996_Spring.md'
        - 'WWIVNews_1995_12.md'
        - 'WWIVNews_1995_09.md'
        - 'WWIVNews_1995_05.md'
        - 'WWIVNews_1994_03.md'
        - 'WWIVNews_1994_01.md'
        - 'WWIVNews_1993_06.md'
        - 'WWIVNews_1993_04.md'
        - 'WWIVNews_1993_02.md'
        - 'WWIVNews_1992_11.md'
        - 'WWIVNews_1992_10.md'
        - 'WWIVNews_1992_09.md'
        - 'WWIVNews_1992_08.md'
        - 'WWIVNews_1992_07.md'
        - 'WWIVNews_1992_06.md'
        - 'WWIVNews_1992_05.md'
        - 'WWIVNews_1992_01.md'
        - 'WWIVNews_1991_08.md'
        - 'WWIVNews_1991_06.md'
        - 'WWIVNews_1991_05.md'
        - 'WWIVNews_1991_04.md'
        - 'WWIVNews_1991_03.md'
        - 'WWIVNews_1991_02.md'
        - 'WWIVNews_1991_01.md'
        - 'WWIVNews_Template.md'
        - 'WWIVNews_Playbook.md'