site_name: WWIV BBS 5.0 Documentation
repo_url: https://github.com/wwivbbs/docs/
copyright: 2014+ WWIV Software Services, LLC
pages:
 - 'index.md'
 - 'WWIV_BBS_list.md'
 - 'Installation'
 - 'Configuration'
 - 'Doors'
 - 'Editors'
 - 'Menus_and_Features'
 - 'Nets'
 - 'Tools_and_Utilities'
 - 'Development'
 - 'History'
 - 'WWIVNews'
 - 'WWIVCon'
 - 'license.md'