site_name: WWIV BBS 5.0 Documentation
repo_url: https://github.com/wwivbbs/docs/
copyright: 2014+ WWIV Software Services, LLC
pages:
    - 'index.md'
    - 'WWIV_BBS_list.md'
    - 'license.md'
    - Installation:
        - '/Installation/Installing_on_Windows.md'
        - '/Installation/WWIV_4x_Upgrade.md'
        - '/Installation/Linux_Installation.md'
        - '/Installation/Linux_dosemu_scripts.md'
        - '/Installation/Linux_dosemu_settings.md'
    - Configuration:
        - '/Configuration/Custom_user_messages.md'
        - '/Configuration/dialup.md'
        - '/Configuration/init.md'
        - '/Configuration/logfiles.md'
        - '/Configuration/multinode.md'
        - '/Configuration/taglines.md'
        - '/Configuration/wwivini.md'
    - Telnet:
        - '/Configuration/Telnet/NET2BBS.md'
        - '/Configuration/Telnet/WWIV_5_telnet_server.md'
    - Menus & Features:
        - '/Menus_and_Features/ansi.md'
        - '/Menus_and_Features/eventmgmt.md'
        - '/Menus_and_Features/gfiles.md'
        - '/Menus_and_Features/Main_menu.md'
        - '/Menus_and_Features/Messaging_system.md'
        - '/Menus_and_Features/Slash_menu.md'
        - '/Menus_and_Features/SysOp_menu.md'
        - '/Menus_and_Features/transfers.md'
        - '/Menus_and_Features/User_preferences.md'
        - '/Menus_and_Features/Waiting_for_callers.md'
    - Nets:
        - '/Nets/WWIVNet.md'
        - '/Nets/WWIVNet_Windows.md'
        - '/Nets/WWIVNet_Linux.md'
        - '/Nets/Other_Nets.md'
        - '/Nets/usenet.md'
        - '/Nets/NET37_Docs.md'
        - '/Nets/NET37_Tec_Docs.md'
    - Doors & Chains:
        - '/Doors/Ambroshia.md'
        - '/Doors/BarronRealmsElite.md'
        - '/Doors/Darkness.md'
        - '/Doors/DoorMUD.md'
        - '/Doors/doorteos.md'
        - '/Doors/index.md'
        - '/Doors/LORD.md'
        - '/Doors/LORD2.md'
        - '/Doors/MechWars.md'
        - '/Doors/TradeWars2002.md'
    - Editors:
        - '/Editors/wwivedit.md'
        - '/Editors/QuickBBS-Editors.md'
    - Tools and Utilities:
        - '/Configuration/Tools_and_Utilities/clients.md'
        - '/Configuration/Tools_and_Utilities/fix.md'
    - History:
        - '/History/index.md'
        - '/History/WWIV_Open_Source_Announcement.md'
        - '/History/newsysop.md'
        - '/History/Original-Ideas-for-5.0-from-July-1999.md'
        - '/History/links.md'
    - Development:
        - '/Development/build_WWIV_5.md'
        - '/Development/WWIV_releases_and_versioning.md'
    - WWIVCon:
        - '/WWIVCon/WWIVCon_1994.md'
        - '/WWIVCon/WWIVCon_1995.md'
        - '/WWIVCon/WWIVCon_1996.md'
        - '/WWIVCon/WWIVCon_1997.md'
        - '/WWIVCon/WWIVCon_1998.md'
        - '/WWIVCon/WWIVCon_1999.md'
    - WWIVNews:
        - '/WWIVNews/index.md'
        - '/WWIVNews/WWIVNews_201512.md'
        - '/WWIVNews/WWIVNews_2015_12.md'
        - '/WWIVNews/WWIVNews_1996_Spring.md'
        - '/WWIVNews/WWIVNews_1995_12.md'
        - '/WWIVNews/WWIVNews_1995_09.md'
        - '/WWIVNews/WWIVNews_1995_05.md'
        - '/WWIVNews/WWIVNews_1994_03.md'
        - '/WWIVNews/WWIVNews_1994_01.md'
        - '/WWIVNews/WWIVNews_1993_06.md'
        - '/WWIVNews/WWIVNews_1993_04.md'
        - '/WWIVNews/WWIVNews_1993_02.md'
        - '/WWIVNews/WWIVNews_199201.md'
        - '/WWIVNews/WWIVNews_1992_11.md'
        - '/WWIVNews/WWIVNews_1992_10.md'
        - '/WWIVNews/WWIVNews_1992_09.md'
        - '/WWIVNews/WWIVNews_1992_08.md'
        - '/WWIVNews/WWIVNews_1992_07.md'
        - '/WWIVNews/WWIVNews_1992_06.md'
        - '/WWIVNews/WWIVNews_1992_05.md'
        - '/WWIVNews/WWIVNews_1992_01.md'
        - '/WWIVNews/WWIVNews_1991_08.md'
        - '/WWIVNews/WWIVNews_1991_06.md'
        - '/WWIVNews/WWIVNews_1991_05.md'
        - '/WWIVNews/WWIVNews_1991_04.md'
        - '/WWIVNews/WWIVNews_1991_03.md'
        - '/WWIVNews/WWIVNews_1991_02.md'
        - '/WWIVNews/WWIVNews_1991_01.md'
        - '/WWIVNews/WWIVNews_Template.md'
        - '/WWIVNews/WWIVNews_Playbook.md'